### ISSUE TITLE
Update for 1.7-rc.3's <inputs_for> component?

### ISSUE THREAD

**Issue by waseigo** [LostKobrakai/one-to-many-form#4]
Hello, thank you for posting this example. I have been trying to get it to work by changing `def render(assigns)` to use `<inputs_for>`, after setting phoenix to 1.7-rc.3 in `mix.exs` and updating `core_components.ex`, however with no success.

Any chance you could update this to show how things should be / will be done in the upcoming stable?

**Comment by LostKobrakai** [comment]
Given I PR'ed `<.inputs_for />` it'll eventually find its way into this. There are also upcoming changes to ecto I want to integrate. 

Generally you should be done replacing `<%= for inner <- inputs_for(…) %>` with the component version as well as removing the `Phoenix.HTML.Form.hidden_inputs_for` call.

**Comment by LostKobrakai** [comment]
I've just pushed an update to 1.7.0

**Comment by waseigo** [comment]
Many many thanks!
