### ISSUE TITLE
Update form for Phoenix 1.7.1 Streams

### ISSUE THREAD

**Issue by contra-bit** [LostKobrakai/one-to-many-form#5]
Good day,

thank you very much for these good resources and posts on the forum.
 I am trying to follow your guide to have a nested form in a live view, which I have generated with `phx.gen.live`, but I am failing due to the switch to streams in phoenix 1.7.1. The Socket which has been created with stream does not have *form* or *changeset*.

In this repo all mounts are set up with ` {:ok, assign(socket, base: base, form: to_form(changeset))}`, using streams the mount looks like this: ` {:ok, stream(socket, :polls, Pollable.list_polls())}`

I have created `handle_event` function in `index.ex` and `show.ex`, because events are sent to *index.ex* and not to the *form_component.ex*. My `handle_event`  function for the "add-line" event updates the form. Since the live view generator has moved to streams. I cannot access changeset or form in the socket. 

This is the socket which passed to my `handle_event` function in `poll_live/index.ex`:
```elixir
#Phoenix.LiveView.Socket<
  id: "phx-F04qMcSe7afDuQBD",
  endpoint: TermiWeb.Endpoint,
  view: TermiWeb.PollLive.Index,
  parent_pid: nil,
  root_pid: #PID<0.604.0>,
  router: TermiWeb.Router,
  assigns: %{
    __changed__: %{},
    flash: %{},
    live_action: :new,
    page_title: "New Poll",
    poll: %Termi.Pollable.Poll{
      __meta__: #Ecto.Schema.Metadata<:built, "polls">,
      id: nil,
      anonymous: nil,
      compulsatory: nil,
      description: nil,
      duration: nil,
      expiration: nil,
      title: nil,
      options: [
        %Termi.Pollable.Option{
          __meta__: #Ecto.Schema.Metadata<:built, "options">,
          id: nil,
          datetime: nil,
          poll_id: nil,
          deleted: nil,
          votes: #Ecto.Association.NotLoaded<association :votes is not loaded>,
          inserted_at: nil,
          updated_at: nil
        }
      ],
      inserted_at: nil,
      updated_at: nil
    },
    streams: %{
      __changed__: MapSet.new([]),
      polls: %Phoenix.LiveView.LiveStream{
        name: :polls,
        dom_id: #Function<3.113057034/1 in Phoenix.LiveView.LiveStream.new/3>,
        inserts: [],
        deletes: []
      }
    }
  },
  transport_pid: #PID<0.598.0>,
```

The socket does not contain a form or a changeset. Please excuse confusion, and thank you for the help.

This is how I have implemented the `handle_event` function. It does not update form and serves only as an example: 
```elixir
  def handle_event("add-option", _params, socket) do
     changeset = Termi.Pollable.change_poll(socket.assigns.poll)
     options = Ecto.Changeset.get_field(changeset, :options)

    updated_changeset =
      Ecto.Changeset.put_assoc(changeset, :options, options++ [Pollable.create_poll(%{deleted: false})])

    IO.inspect(socket)
    # TODO Fix changeset and form are not used any more
    socket =  assign(socket, %{form: to_form(updated_changeset), changeset: updated_changeset})

    {:noreply, socket}
  end
 ```

I have tried not using changesets and directly updating the options of poll in the socket with `stream_insert`, but this seems to be very wrong.

Thank you very much :)

This [example](https://codeberg.org/lgh/Termi/src/commit/e12a78dc057b013b65308f7285872f455ebc205d/lib/termi_web/live/poll_live/index.ex#L51), does not add an extra option to the form, because it creates the changeset and form. 

Just in case you want to know, [this](https://codeberg.org/lgh/Termi/src/branch/livemd/termiNotes.md#second-try) is how I have used `phx.gen.live` to create the poll liveview

**Comment by LostKobrakai** [comment]
So streams are all about rendering lists of things without needing to keep their values in memory on the server. So really the goal is that the stream items are no longer available. I'm wondering how this relates to your usecase though. Why do you want/need streams if there are obviously ways of interacting with those items, where you need their data again?
