### ISSUE TITLE
Update blog post to `Ecto.Changeset.get_assoc/3`

### ISSUE THREAD

**Issue by michaelterryio** [LostKobrakai/one-to-many-form#6]
Looks like this can be done now, no?

Your post was extremely helpful for understanding why LV works the way it does and why I've found some parts a bit odd.

Also, I wish the `phx.gen.live` CRUD scaffolding generated a self-contained LV form like this instead of using LiveComponent.

**Comment by LostKobrakai** [comment]
I've been meaning to do this for a while. This repo is updated. The blog post will be shortly one CI is done.
