### ISSUE TITLE
The Add button not work because handle_event("submit", _,_)

### ISSUE THREAD

**Issue by manhtranlinh** [LostKobrakai/one-to-many-form#9]
Hi,
In your example in callback function  
 `handle_event("submit", %{"groceries_list" => params}, socket) `
, you used 
 `changeset = GroceriesList.changeset(socket.assigns.base, params) `
This will make the Add button not work, because the change which is updated in handle_event "add-line" will be ignored. 
I changed to the following: 
` changeset = GroceriesList.changeset(socket.assigns.form.source, groceries_list_params)` 
 it will work as expected. Please help to check.

**Comment by LostKobrakai** [comment]
Can you describe more closely what isn't working? As explained in the related blog post using the changeset shouldn't be needed to save the changes. The submitted params based on the forms state should be enough.

**Comment by manhtranlinh** [comment]
With the your current handle_event callback, we can not use the Add button(click button, but the new line is not display), because submit event does not get the change from add-line event. 
`def handle_event("submit", %{"groceries_list" => params}, socket) do
  changeset = GroceriesList.changeset(socket.assigns.base, params)
  case Ecto.Changeset.apply_action(changeset, :insert) do
    {:ok, data} ->
      socket = put_flash(socket, :info, "Submitted successfully")
      {:noreply, init(socket, data)}
    {:error, changeset} ->
      {:noreply, assign(socket, form: to_form(changeset))}
  end`

**Comment by LostKobrakai** [comment]
I can add new lines just fine here. The idea is that the `"add-line"` handler makes the form rerender on the client, so it then submits fields for the new line when submitting the form. 

So again, which one is not working for you? Clicking the add line button and have the new line show up in the browser or submitting the form with the new line already present?

**Comment by manhtranlinh** [comment]
With me the add line button did not work: no new line show up in the browser. 
If I changed the handle_event("submit",-,_) and use `changeset = GroceriesList.changeset(socket.assigns.form.source, groceries_list_params)`,  the add line button will work.

**Comment by LostKobrakai** [comment]
Are you sure you're using `<button type="button">`? Because clicking that button is not supposed to trigger the `"submit"` handler at all.

**Comment by manhtranlinh** [comment]
Yes, I am using `<button type="button">`. 

  `@impl true`
  `def render(assigns) do`
    `~H"""`
    ` <div><.header> <:subtitle>Use this form to manage invoice records.</:subtitle> </.header>`
    `  <.simple_form id={@id} for={@form} phx-change="validate" phx-submit="submit">`
      `  <.input field={@form[:email]} label="Email" />`

 ```
       <fieldset class="flex flex-col gap-2">
          <legend>Groceries</legend>
          <.inputs_for :let={f_line} field={@form[:lines]}>
            <.line f_line={f_line} />
          </.inputs_for>
          <.button class="mt-2" type="button" phx-click="add-line">Add</.button>
        </fieldset>

        <:actions>
          <.button>Save</.button>
        </:actions>
      </.simple_form>
    </div>
    """
```
`  end`

**Comment by LostKobrakai** [comment]
Then I'm not sure why the `"submit"` ahdnler would be called when you click on the button. 

```
[debug] HANDLE EVENT
  View: OneToManyWeb.ListLive
  Event: "add-line"
  Parameters: %{"value" => ""}
[debug] Replied in 5ms
```

this is all I see in the iex console when clicking the add button. The form doesn't submit.

**Comment by manhtranlinh** [comment]
I have just tested again, I change to the same your example, now it work. May be something wrong with my development environment few days ago. 
Thanks and so sorry for this wrong.

**Comment by LostKobrakai** [comment]
No worries.
